src/Entity/Biere.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BiereRepository")
 * @UniqueEntity(
 *     fields={"nom", "id_brasserie"}
 * )
 */
class Biere
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $robe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ibu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $abv;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Brasserie", inversedBy="bieres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_brasserie;


    public function __construct()
    {
        $this->setDateCreation(new \DateTime('now'));
    }

    public function __toString()
    {
        return $this->getNom();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): string {

         return (new Slugify())->slugify($this->nom);
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getRobe(): ?string
    {
        return $this->robe;
    }

    public function setRobe(?string $robe): self
    {
        $this->robe = $robe;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIbu(): ?int
    {
        return $this->ibu;
    }

    public function setIbu(?int $ibu): self
    {
        $this->ibu = $ibu;

        return $this;
    }

    public function getAbv(): ?string
    {
        return $this->abv;
    }

    public function setAbv(?string $abv): self
    {
        $this->abv = $abv;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getIdBrasserie(): ?Brasserie
    {
        return $this->id_brasserie;
    }

    public function setIdBrasserie(?Brasserie $id_brasserie): self
    {
        $this->id_brasserie = $id_brasserie;

        return $this;
    }

}

src/Entity/Checklist.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChecklistRepository")
 */
class Checklist
{
    const SERVICE =  array("Pression","Bouteille","Canette");

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Biere")
     * @ORM\JoinColumn(nullable=false)
     */
    private $biere;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Revendeur")
     * @ORM\JoinColumn(nullable=true)
     */
    private $revendeur;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 0,
     *      max = 10,
     * )
     */
    private $note;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $service;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;


    public function __construct()
    {
        $this->setDateCreation(new \DateTime('now'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBiere(): ?Biere
    {
        return $this->biere;
    }

    public function setBiere(?Biere $biere): self
    {
        $this->biere = $biere;

        return $this;
    }

    public function getRevendeur(): ?Revendeur
    {
        return $this->revendeur;
    }

    public function setRevendeur(?Revendeur $revendeur): self
    {
        $this->revendeur = $revendeur;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(string $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }
}

src/Form/ChecklistType.php
<?php

namespace App\Form;

use App\Entity\Checklist;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChecklistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('note', IntegerType::class)
            ->add('revendeur')
            ->add('service', ChoiceType::class, [
                'required' => false,
                'choices' => $this->getChoices()
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Checklist::class,
        ]);
    }

    private function getChoices()
    {
        $choices = Checklist::SERVICE;
        $output=[];
        foreach ($choices as $k => $v){
            $output[$v]=$v;
        }
        return $output;
    }
}

src/Controller/ChecklistController.php
<?php

namespace App\Controller;

use App\Entity\Biere;
use App\Entity\BiereSearch;
use App\Entity\Checklist;
use App\Form\ChecklistType;
use App\Repository\BiereRepository;
use App\Form\BiereSearchType;
use App\Repository\ChecklistRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChecklistController extends AbstractController
{
    /**
     * @var ChecklistRepository
     */
    private $checklistRepository;

    public function __construct(ChecklistRepository $checklistRepository)
    {
        $this->checklistRepository = $checklistRepository;
    }

    /**
     * @Route("checklist", name="checklist")
     * @param BiereRepository $repository
     * @param Request $request
     * @return Response
     */
    public function index(BiereRepository $biereRepository, Request $request): Response
    {
        $search = new BiereSearch();
        $form = $this->createForm(BiereSearchType::class, $search);
        $form->handleRequest($request);
        $bieres=$biereRepository->listBiereLikeNomBiereOuBrasserie($search);
        $nbBiere = $this->checklistRepository->nbBiere($this->getUser());
        $nbBiereDistinct=$this->checklistRepository->nbBiereDistinct($this->getUser());

        return $this->render(
            'checklist/show.html.twig',[
            'bieres' => $bieres,
            'nbBiere' => $nbBiere,
            'nbBiereDistinct' => $nbBiereDistinct,
            'form' => $form->createView()
        ]
        );
    }

    /**
     * @Route("checklist/ajoutBiere/{slug}-{id}", name="ajoutBiere", requirements={"slug":"[a-z0-9\-]*"})
     * @param Request $request
     * @param Biere $biere
     * @return Response
     */
    public function new(Request $request, Biere $biere) :Response
    {
        $checklist = new Checklist();
        $checklist->setUser($this->getUser());
        $checklist->setBiere($biere);
        $form = $this->createForm(ChecklistType::class, $checklist);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($checklist);
            $entityManager->flush();

            return $this->redirectToRoute('checklist');
        }
        return $this->render('checklist/ajoutBiere.html.twig', [
            'biere' => $biere,
            'form' => $form->createView()
        ] );
    }

    /**
     * @Route("stats", name="stats")
     * @return Response
     */
    public function statistique() :Response
    {
        $nbBiere=$this->checklistRepository->nbBiere($this->getUser());
        $nbBiereDistinct=$this->checklistRepository->nbBiereDistinct($this->getUser());
        dump($nbBiereDistinct);
        $nbBiereDistinctType=$this->checklistRepository->nbBiereDistinctType($this->getUser());
        dump($nbBiereDistinctType);
        $nbBiereDistinctOrigineBrasseur=$this->checklistRepository->nbBiereDistinctOrigineBrasseur($this->getUser());
        dump($nbBiereDistinctOrigineBrasseur);
        $biereFavorites=$this->checklistRepository->biereFavorites($this->getUser());
        dump($biereFavorites);

        return $this->render(
            'checklist/statistique.html.twig',[
                'nbBiere' => $nbBiere,
                'nbBiereDistinct' => $nbBiereDistinct,
                'nbBiereDistinctType'=> $nbBiereDistinctType,
                'nbBiereDistinctOrigineBrasseur' => $nbBiereDistinctOrigineBrasseur,
                'biereFavorites' => $biereFavorites
            ]
        );
    }
}

templates/checklist/ajoutBiere.html.twig
{% extends 'base.html.twig' %}

{% block title %}Boire {{ biere.nom }} {% endblock %}

{% block body %}
    {{ form_start(form) }}
    <h1> Ajouter
        <a class="text-dark" href="{{ path('biere.info', {id: biere.id, slug: biere.slug})}}">
            {{ biere.nom }}
        </a>
    </h1>
    <div class="form-group">
        <div class="col-md-4"> {{ form_row(form.note) }} </div>
    </div>
    <div class="form-group">
        <div class="col-md-4">
            {{ form_row(form.revendeur) }}
            <a role="button" href="{{ path('revendeur.create') }}" class="btn btn-secondary">Ajouter un revendeur</a>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-4"> {{ form_row(form.service) }} </div>
    </div>
    <button class="btn btn-dark" type="submit">Boire</button>
    {{ form_end(form) }}
{% endblock %}

templates/checklist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Checklist{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-7">
                <h1>Checklist de {{app.user.pseudo}}</h1>
            </div>
            <div class="col-md-4 ">
                <h3>
                    <h3> {{ nbBiere }} {% if nbBiere>=1 %}bières bues{% else %}bière bue{% endif %}</h3>
                    <h3> {{ nbBiereDistinct }} {% if nbBiereDistinct>=1 %}bières différentes{% else %}bière différente{% endif %}</h3>
                </h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="col">
                    {{ form_row(form.nom) }}
                </div>
                <div class="col">
                    <button class="btn btn-dark" type="submit">Chercher</button>
                </div>
                <div class="col">
                    <a role="button" href="{{ path('biere.create') }}" class="btn btn-secondary">Ajouter une bière si vous ne la trouvez pas</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            {{ form_end(form) }}
            {% if bieres==null %}
                <h4>Aucun résultat trouver</h4>
            {% endif %}
            {% for biere in bieres %}
                <div class="card">
                    <div class="card-body" >
                        <h3>
                            <a class="text-dark" href="{{ path('biere.info', {id: biere.id, slug: biere.slug})}}">
                               {{ biere.nom }}
                            </a>
                            <h5>
                                de la brasserie {{ biere.idBrasserie }}
                                <a role="button" href="{{ path('ajoutBiere', {id: biere.id, slug: biere.slug} ) }}" class="btn btn-success float-right">Boire</a>
                            </h5>
                         </h3>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/checklist/statistique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stats{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-7">
                <h1>Statistiques de {{app.user.pseudo}}</h1>
            </div>
            <div class="col-md-4 ">
                <h3>
                    <h3> {{ nbBiere }} {% if nbBiere>=1 %}bières bues{% else %}bière bue{% endif %}</h3>
                    <h3> {{ nbBiereDistinct }} {% if nbBiereDistinct>=1 %}bières différentes{% else %}bière différente{% endif %}</h3>
                </h3>
            </div>
        </div>
    </div>



    {%  if nbBiere > 0 %}
        <table class="table table-borderless  text-center">
            <thead>
                <tr>
                    <th>Par Type</th>
                    <th> Par Origine</th>
                    <th>Bières Favorites</th>
                </tr>
            </thead>
            <tbody >
                <tr>
                    <td>
                        <table class="table table-borderless text-center">
                            <tbody>
                                {% for result in nbBiereDistinctType   %}
                                   <tr><td><h5>{{ result.type | capitalize}}</h5></td><td><h3>{{ result.nb }}</h3></td></tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless text-center">
                            <tbody>
                            {% for result in nbBiereDistinctOrigineBrasseur   %}
                                <tr><td><h5>{{ result.pays | capitalize }}</h5></td><td><h3>{{ result.nb }}</h3></td></tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless text-center">
                            <tbody>
                            {% for result in biereFavorites   %}
                                <tr><td><h5>{{ result.nom | capitalize }}</h5></td><td><h3>{{ result.nb }}</h3></td></tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>

        {% else %}
    {% endif %}




    <div class="container">

        </div>
{% endblock %}